# Core Feast Configuration
#
# This file defines Feast feature store connections for the core service.
# For specific use cases, you should create a custom feast_config.yaml file
# in your application's config directory.

feast:
  sources:
    # Example of a Feast feature store configuration
    # Replace or extend this with your actual feature stores
    default:
      repo_path: "./feature_repo"
      project: "default"
      entity_key_serialization_version: 2
      
      # Example feature service definitions
      feature_services:
        example_features:
          features:
            - "example:feature1"
            - "example:feature2"
            - "example:feature3"