# Mock Services Configuration for Customer 360 Demo

# Database service mock
database:
  sources:
    default:
      type: http
      connection:
        url: "http://localhost:5000/api/v1/database"
        timeout: 5

# API services mock
api:
  sources:
    credit:
      url: "http://localhost:5000/api/v1/credit"
      timeout: 5

# Feature store mock
feast:
  sources:
    default:
      url: "http://localhost:5000/api/v1/feast"
      timeout: 5

# ML service mock  
ml:
  sources:
    default:
      url: "http://localhost:5000/api/v1/ml"
      timeout: 5