# Global Configuration for Iris Example

app:
  name: orchestrator-api-service
  environment: development
  debug: true
  api_base_path: /api

server:
  host: 0.0.0.0
  port: 8080
  workers: 4
  log_level: info
  use_https: false

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_to_file: false
  log_file_path: logs/app.log
  log_file_rotation: 1 day

performance:
  cache_enabled: true
  cache_ttl_seconds: 300
  response_compression: true

# Cross-cutting concerns
cors:
  enabled: true
  allow_origins: ["*"]
  allow_methods: ["*"]
  allow_headers: ["*"]

auth:
  enabled: false
  jwt_secret: "change_me_in_production"
  token_expiry_minutes: 60
  refresh_token_expiry_days: 7