# Example Configuration

app:
  name: orchestrator-example
  environment: development
  debug: true
  api_base_path: /api

server:
  host: 0.0.0.0
  port: 8000
  workers: 1
  log_level: info
  use_https: false

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_to_file: true
  log_file_path: example.log
  log_file_rotation: 1 day

performance:
  cache_enabled: true
  cache_ttl_seconds: 60
  response_compression: true

# Cross-cutting concerns
cors:
  enabled: true
  allow_origins: ["*"]
  allow_methods: ["*"]
  allow_headers: ["*"]

auth:
  enabled: false
  jwt_secret: "example_secret_key"
  token_expiry_minutes: 60
  refresh_token_expiry_days: 7