# Customer 360 Domain Configuration
# Example-specific configuration for the Customer 360 view

domain_name: customer_360
description: "Customer 360 view - combines data from multiple sources"

endpoints:
  get:
    description: "Get a comprehensive customer 360 view"
    data_sources:
      - name: customer_profile
        type: database
        source_id: default
        operation: get_customer
        params:
          customer_id: "$request.customer_id"
      
      - name: customer_features
        type: database
        source_id: default
        operation: get_customer_features
        params:
          customer_id: "$request.customer_id"
      
      - name: credit_score
        type: database
        source_id: default
        operation: get_customer_credit_score
        params:
          customer_id: "$request.customer_id"
      
      - name: recent_orders
        type: database
        source_id: default
        operation: get_customer_recent_orders
        params:
          customer_id: "$request.customer_id"
          limit: 5
      
      - name: churn_prediction
        type: database
        source_id: default
        operation: get_customer_churn_prediction
        params:
          customer_id: "$request.customer_id"
    
    response_mapping:
      customer_id: "$customer_profile.customer_id"
      personal_info:
        name: "$customer_profile.name"
        email: "$customer_profile.email"
        phone: "$customer_profile.phone"
        address: "$customer_profile.address"
        date_of_birth: "$customer_profile.date_of_birth"
      account_info:
        created_at: "$customer_profile.created_at"
        credit_score: "$credit_score.score"
        risk_tier: "$credit_score.risk_tier"
      behavior:
        lifetime_value: "$customer_features.customer_lifetime_value"
        days_since_last_purchase: "$customer_features.days_since_last_purchase"
        purchase_frequency: "$customer_features.purchase_frequency"
        average_order_value: "$customer_features.average_order_value"
      recent_orders: "$recent_orders[*]"
      predictions:
        churn_probability: "$churn_prediction.probability"
        churn_risk_level: "$churn_prediction.risk_level"
        next_best_offer: "$churn_prediction.recommendation"