# Sample Domain Feast Configuration

feast:
  sources:
    # Domain-specific Feast feature store configuration
    sample_features:
      repo_path: "./feature_repo/sample_domain"
      project: "sample_domain"
      entity_key_serialization_version: 2
      
      # Domain-specific feature service definitions
      feature_services:
        domain_features:
          features:
            - "sample:feature1"
            - "sample:feature2"
            - "sample:feature3"