# Loan Prediction Domain Configuration

domain_name: loan_prediction
description: "Loan approval prediction service using features from database"

endpoints:
  predict:
    description: "Predict loan approval probability using features from database"
    endpoint_type: "composite"
    data_sources:
      # First, retrieve applicant features from database
      - name: applicant_features
        type: database
        source_id: default
        operation: get_applicant_features
        params:
          applicant_id: "$request.applicant_id"
      
      # Then send those features to ML model for scoring
      - name: loan_prediction
        type: ml
        source_id: loan_model
        operation: predict_loan_approval
        params:
          features:
            # Map database fields to feature names expected by the model
            applicant_id: "$applicant_features.applicant_id"
            age: "$applicant_features.age"
            annual_income: "$applicant_features.annual_income"
            credit_score: "$applicant_features.credit_score"
            debt_to_income: "$applicant_features.debt_to_income"
            employment_years: "$applicant_features.employment_years"
            loan_amount: "$applicant_features.loan_amount"
            loan_term: "$applicant_features.loan_term"
            current_loans: "$applicant_features.current_loans"
            total_current_debt: "$applicant_features.total_current_debt"
            approval_ratio: "$applicant_features.approval_ratio"
    
    response_mapping:
      applicant_id: "$applicant_features.applicant_id"
      loan_details:
        amount: "$applicant_features.loan_amount"
        term: "$applicant_features.loan_term"
        purpose: "$applicant_features.loan_purpose"
      financial_summary:
        annual_income: "$applicant_features.annual_income"
        credit_score: "$applicant_features.credit_score"
        debt_to_income: "$applicant_features.debt_to_income"
        employment_years: "$applicant_features.employment_years"
      prediction:
        approval_probability: "$loan_prediction.probability"
        decision: "$loan_prediction.decision"
        risk_tier: "$loan_prediction.risk_tier"
        suggested_interest_rate: "$loan_prediction.suggested_interest_rate"
      key_factors: "$loan_prediction.factors"
  
  get_applicant_data:
    description: "Get detailed applicant data from multiple tables"
    endpoint_type: "composite"
    data_sources:
      - name: applicant
        type: database
        source_id: default
        operation: get_applicant
        params:
          applicant_id: "$request.applicant_id"
      
      - name: financial
        type: database
        source_id: default
        operation: get_financial_data
        params:
          applicant_id: "$request.applicant_id"
      
      - name: history
        type: database
        source_id: default
        operation: get_loan_history
        params:
          applicant_id: "$request.applicant_id"
    
    response_mapping:
      applicant_id: "$applicant.applicant_id"
      name: "$applicant.name"
      email: "$applicant.email"
      age: "$applicant.age"
      created_at: "$applicant.created_at"
      financial_data:
        annual_income: "$financial.annual_income"
        credit_score: "$financial.credit_score"
        debt_to_income: "$financial.debt_to_income"
        employment_years: "$financial.employment_years"
        loan_amount: "$financial.loan_amount"
        loan_term: "$financial.loan_term"
        loan_purpose: "$financial.loan_purpose"
      loan_history:
        previous_applications: "$history.previous_applications"
        approved_loans: "$history.approved_loans"
        rejected_loans: "$history.rejected_loans"
        current_loans: "$history.current_loans"
        total_current_debt: "$history.total_current_debt"