# Global orchestrator configuration
app:
  name: "Simple Orchestrator API Project"
  description: "Demonstration of Orchestrator API Service as a library"
  version: "0.1.0"
  
server:
  host: "0.0.0.0"
  port: 8000
  
logging:
  level: "INFO"
  
execution:
  timeout: 30000  # Default timeout in milliseconds
  
api:
  prefix: "/orchestrator"
  docs_url: "/docs"
  redoc_url: "/redoc"