# Iris Example Database Configuration

database:
  sources:
    default:
      connection_string: "sqlite:///example/iris_example/iris_example.db"
      pool_size: 5
      max_overflow: 10
      pool_timeout: 30
      pool_recycle: 1800
      connect_args:
        check_same_thread: false

  operations:
    get_iris_by_id:
      query: "SELECT * FROM iris_flowers WHERE id = :flower_id"
      params:
        - flower_id
    
    get_iris_sample:
      query: "SELECT * FROM iris_flowers ORDER BY RANDOM() LIMIT :limit"
      params:
        - limit
    
    get_iris_by_species:
      query: "SELECT * FROM iris_flowers WHERE species = :species"
      params:
        - species
    
    get_all_species:
      query: "SELECT DISTINCT species FROM iris_flowers"
      params: []