# Core Database Configuration
#
# This file defines database connections and operations for the core service.
# For specific use cases, you should create a custom database.yaml file
# in your application's config directory.

database:
  sources:
    # Example of a database source configuration
    # Replace or extend this with your actual database connections
    default:
      connection_string: "sqlite:///orchestrator.db"
      pool_size: 5
      max_overflow: 10
      pool_timeout: 30
      pool_recycle: 1800
      connect_args:
        check_same_thread: false

  # Example database operations
  # Define your own operations based on your schema
  operations:
    # Example operation to get a record by ID
    get_by_id:
      query: "SELECT * FROM ${table} WHERE id = :id"
      params:
        - id
        - table