# Database Configuration

database:
  sources:
    default:
      connection_string: "sqlite:///customer360.db"
      pool_size: 5
      max_overflow: 10
      pool_timeout: 30
      pool_recycle: 1800
      connect_args:
        check_same_thread: false

  operations:
    get_customer:
      query: "SELECT * FROM customers WHERE customer_id = :customer_id"
      params:
        - customer_id
    
    get_customer_recent_orders:
      query: "SELECT * FROM orders WHERE customer_id = :customer_id ORDER BY order_date DESC LIMIT :limit"
      params:
        - customer_id
        - limit
    
    get_customer_features:
      query: "SELECT * FROM customer_features WHERE customer_id = :customer_id"
      params:
        - customer_id
    
    get_customer_credit_score:
      query: "SELECT * FROM credit_scores WHERE customer_id = :customer_id"
      params:
        - customer_id
    
    get_customer_churn_prediction:
      query: "SELECT * FROM churn_predictions WHERE customer_id = :customer_id ORDER BY created_at DESC LIMIT 1"
      params:
        - customer_id
