# ML service configurations for the churn prediction model
sources:
  churn_model:
    base_url: "http://localhost:5001"
    models:
      default:
        endpoint: "/predict/churn"
        timeout: 30
        headers:
          Content-Type: "application/json"