# Customer Domain Configuration

domain_name: customers
description: "Customer management operations"

# API endpoint configurations
endpoints:
  list:
    description: "List customers with pagination"
    data_sources:
      - name: customers_list
        type: database
        operation: list_customers
        params:
          limit: "$request.limit"
          offset: "$request.offset"
    primary_source: customers_list
    response_mapping: null  # Use the primary source results directly
  
  get:
    description: "Get a single customer by ID"
    data_sources:
      - name: customer_data
        type: database
        operation: get_customer
        params:
          customer_id: "$request.customer_id"
    primary_source: customer_data
    response_mapping: null  # Use the primary source results directly
  
  create:
    description: "Create a new customer"
    data_sources:
      - name: new_customer
        type: database
        operation: create_customer
        params:
          customer_data: "$request"
    primary_source: new_customer
    response_mapping: null  # Use the primary source results directly
  
  update:
    description: "Update an existing customer"
    data_sources:
      - name: updated_customer
        type: database
        operation: update_customer
        params:
          customer_id: "$request.customer_id"
          customer_data: "$request"
    primary_source: updated_customer
    response_mapping: null  # Use the primary source results directly
  
  # Example of an endpoint that combines data from multiple sources
  get_enriched:
    description: "Get customer data enriched with features and predictions"
    data_sources:
      - name: customer_data
        type: database
        operation: get_customer
        params:
          customer_id: "$request.customer_id"
      
      - name: customer_features
        type: feast
        operation: get_customer_features
        params:
          customer_id: "$request.customer_id"
      
      - name: credit_score
        type: api
        operation: get_customer_credit_score
        params:
          customer_id: "$request.customer_id"
      
      - name: churn_prediction
        type: ml
        operation: predict_customer_churn
        params:
          customer_features: "$customer_features"
    
    # Response mapping to combine data from all sources
    response_mapping:
      customer_id: "$customer_data.customer_id"
      name: "$customer_data.name"
      email: "$customer_data.email"
      phone: "$customer_data.phone"
      address: "$customer_data.address"
      date_of_birth: "$customer_data.date_of_birth"
      created_at: "$customer_data.created_at"
      updated_at: "$customer_data.updated_at"
      credit_score: "$credit_score.score"
      features:
        lifetime_value: "$customer_features.customer_lifetime_value"
        days_since_last_purchase: "$customer_features.days_since_last_purchase"
        purchase_frequency: "$customer_features.purchase_frequency"
      predictions:
        churn_probability: "$churn_prediction.probability"
        churn_risk_level: "$churn_prediction.risk_level"
