# Iris Example Domain Configuration
domain_id: iris_example
description: "Iris flower classification example with database to ML pattern"

endpoints:
  # Endpoint using HTTP model
  predict:
    description: "Predict iris species using flower features from database"
    endpoint_type: "composite"
    data_sources:
      # Get iris flower data from database
      - name: iris_data
        type: database
        source_id: default
        operation: get_iris_by_id
        params:
          flower_id: "$request.path_params.flower_id"
      
      # Get prediction from ML model
      - name: prediction
        type: ml
        source_id: http_model
        operation: predict
        params:
          features:
            sepal_length: "$iris_data.sepal_length"
            sepal_width: "$iris_data.sepal_width"
            petal_length: "$iris_data.petal_length"
            petal_width: "$iris_data.petal_width"
    
    # Map the response
    response_mapping:
      flower_id: "$iris_data.id"
      features:
        sepal_length: "$iris_data.sepal_length"
        sepal_width: "$iris_data.sepal_width"
        petal_length: "$iris_data.petal_length"
        petal_width: "$iris_data.petal_width"
      actual_species: "$iris_data.species"
      prediction: "$prediction.prediction"
  
  # Endpoint using locally loaded model
  predict_local:
    description: "Predict iris species using locally loaded model"
    endpoint_type: "composite"
    data_sources:
      # Get iris flower data from database
      - name: iris_data
        type: database
        source_id: default
        operation: get_iris_by_id
        params:
          flower_id: "$request.path_params.flower_id"
      
      # Get prediction from local ML model
      - name: prediction
        type: ml
        source_id: local_model
        operation: predict
        params:
          features:
            sepal_length: "$iris_data.sepal_length"
            sepal_width: "$iris_data.sepal_width"
            petal_length: "$iris_data.petal_length"
            petal_width: "$iris_data.petal_width"
    
    # Map the response
    response_mapping:
      flower_id: "$iris_data.id"
      features:
        sepal_length: "$iris_data.sepal_length"
        sepal_width: "$iris_data.sepal_width"
        petal_length: "$iris_data.petal_length"
        petal_width: "$iris_data.petal_width"
      actual_species: "$iris_data.species"
      prediction: "$prediction.prediction"
      loaded_from: "local_artifact"
  
  
  # Endpoint to compare predictions from both models
  compare:
    description: "Compare predictions from HTTP and locally loaded models"
    endpoint_type: "composite"
    data_sources:
      # Get iris flower data from database
      - name: iris_data
        type: database
        source_id: default
        operation: get_iris_by_id
        params:
          flower_id: "$request.path_params.flower_id"
      
      # Get prediction from HTTP model
      - name: http_prediction
        type: ml
        source_id: http_model
        operation: predict
        params:
          features:
            sepal_length: "$iris_data.sepal_length"
            sepal_width: "$iris_data.sepal_width"
            petal_length: "$iris_data.petal_length"
            petal_width: "$iris_data.petal_width"
      
      # Get prediction from local model
      - name: local_prediction
        type: ml
        source_id: local_model
        operation: predict
        params:
          features:
            sepal_length: "$iris_data.sepal_length"
            sepal_width: "$iris_data.sepal_width"
            petal_length: "$iris_data.petal_length"
            petal_width: "$iris_data.petal_width"
    
    # Map the response to compare predictions
    response_mapping:
      flower_id: "$iris_data.id"
      features:
        sepal_length: "$iris_data.sepal_length"
        sepal_width: "$iris_data.sepal_width"
        petal_length: "$iris_data.petal_length"
        petal_width: "$iris_data.petal_width"
      actual_species: "$iris_data.species"
      predictions:
        http_model: "$http_prediction.prediction"
        local_model: "$local_prediction.prediction"
      agreement: "$http_prediction.prediction.class_name == $local_prediction.prediction.class_name"
  
  # Endpoint to query random iris samples
  samples:
    description: "Get random iris flower samples"
    endpoint_type: "database"
    data_sources:
      - name: iris_samples
        type: database
        source_id: default
        operation: get_iris_sample
        params:
          limit: "$request.query_params.limit || 5"
    primary_source: iris_samples
    
  # Endpoint to get all species
  species:
    description: "Get all iris species"
    endpoint_type: "database"
    data_sources:
      - name: species_list
        type: database
        source_id: default
        operation: get_all_species
        params: {}
    primary_source: species_list